# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 860)
        MainWindow.setMinimumSize(QtCore.QSize(640, 860))
        MainWindow.setMaximumSize(QtCore.QSize(640, 860))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(64, 64, 64);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 600, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(100, 200, 200);\n"
                                 "font: 24pt \"Consolas\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 90, 621, 761))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("font: 75 16pt \"Consolas\";\n"
                                 "color: rgb(100, 200, 200);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 0, 540, 60))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayoutWidget.setStyleSheet("QLineEdit {"
                                            "font: 12pt \"Consolas\";"
                                            "color: white;"
                                            "background-color: rgb(96, 96, 96);"
                                            "border-color: white;"
                                            "border-radius: 12px;"
                                            "border-style: outset;"
                                            "border-width: 2px;}"
                                            "QLineEdit:focus {"
                                            "background-color: teal;}")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.usernameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usernameInput.setFrame(True)
        self.usernameInput.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameInput.setObjectName("usernameInput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameInput)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.profileInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.profileInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.profileInput.setAlignment(QtCore.Qt.AlignCenter)
        self.profileInput.setObjectName("profileInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.profileInput)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(120, 140, 380, 350))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setSpacing(8)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.tamingLevel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.tamingLevel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tamingLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.tamingLevel.setObjectName("tamingLevel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tamingLevel)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.farmingLevel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.farmingLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.farmingLevel.setObjectName("farmingLevel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.farmingLevel)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.miningLevel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.miningLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.miningLevel.setObjectName("miningLevel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.miningLevel)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.combatLevel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.combatLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.combatLevel.setObjectName("combatLevel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.combatLevel)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.foragingLevel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.foragingLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.foragingLevel.setObjectName("foragingLevel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.foragingLevel)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.fishingLevel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.fishingLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.fishingLevel.setObjectName("fishingLevel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.fishingLevel)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.enchantingLevel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.enchantingLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.enchantingLevel.setObjectName("enchantingLevel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.enchantingLevel)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.alchemyLevel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.alchemyLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.alchemyLevel.setObjectName("alchemyLevel")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.alchemyLevel)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.carpentryLevel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.carpentryLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.carpentryLevel.setObjectName("carpentryLevel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.carpentryLevel)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.runecraftingLevel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.runecraftingLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.runecraftingLevel.setObjectName("runecraftingLevel")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.runecraftingLevel)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.socialLevel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.socialLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.socialLevel.setObjectName("socialLevel")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.socialLevel)
        self.processDisplay = QtWidgets.QTextBrowser(self.frame)
        self.processDisplay.setGeometry(QtCore.QRect(40, 600, 540, 160))
        self.processDisplay.setStyleSheet("font: 12pt \"Consolas\";"
                                          "background-color: rgb(96, 96, 96);"
                                          "color: white;"
                                          "border-radius: 16px;"
                                          "border-width: 2px;"
                                          "border-style: solid;"
                                          "border-color: white;")
        self.processDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.processDisplay.setFrameShadow(QtWidgets.QFrame.Plain)
        self.processDisplay.setObjectName("processDisplay")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 60, 540, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayoutWidget.setStyleSheet("QPushButton {"
                                                  "background-color: rgb(96, 96, 96); "
                                                  "border-radius: 16px; "
                                                  "border-style: outset; "
                                                  "border-width: 2px; "
                                                  "border-color: white; "
                                                  "padding: 2px;} "
                                                  "QPushButton:pressed {"
                                                  "background-color: white;} "
                                                  "QPushButton:hover {"
                                                  "border-color: teal;}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.clearButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Skill Display"))
        self.label.setText(_translate("MainWindow", "Skill Display"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_14.setText(_translate("MainWindow", "Profile:"))
        self.label_3.setText(_translate("MainWindow", "Taming"))
        self.tamingLevel.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Farming"))
        self.farmingLevel.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Mining"))
        self.miningLevel.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Combat"))
        self.combatLevel.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Foraging"))
        self.foragingLevel.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Fishing"))
        self.fishingLevel.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Enchanting"))
        self.enchantingLevel.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Alchemy"))
        self.alchemyLevel.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "Carpentry"))
        self.carpentryLevel.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "Runecrafting"))
        self.runecraftingLevel.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Social"))
        self.socialLevel.setText(_translate("MainWindow", "0"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
